### ISSUE TITLE
Proto dungeon crawler

### ISSUE THREAD

**Issue by Blublusse** [Cybierre-Koffee-Studio/GameOff2023#2]
# Le concept (sera amené à s'enrichir)

Un jeu de placement de tuiles sur un plateau qui bascule sur un axe.

Le joueur doit maintenir le plateau relativement équilibré.

Les tuiles sont des éléments d'un donjon que le joueur place pour former des couloirs.

Le joueur dispose d'un personnage sous forme d'une figurine qu'il déplace dans le donjon et qui démarre au centre du plateau. Son objectif est de construire un donjon permettant à son personnage d'aller chercher une clé située sur une tuile placée à un endroit inaccessible en début de partie pour rejoindre une porte de sortie située sur une tuile également inaccessible en début de partie.

## Gameplay

Le jeu se joue en tour par tour.

Le joueur a devant lui 5 tuiles tirées au hasard, à chaque tour il peut :
- soit placer une nouvelle tuile qui doit être adjacente à une tuile existante et continuer le plan du donjon de manière logique
- soit déplacer le personnage

A chaque fin de tour, en fonction de l'endroit où est placée la nouvelle tuile ou de l'endroit où le personnage se situe, l'équilibre du plateau est ajusté.

Si le plateau est trop déséquilibré, la partie est perdue.

# TODO
- [x] plateau sur 1 axe
- modèles de tuiles :
  - [x] centrale
  - [x] en T
  - [x] en coin
  - [x] en couloir
- [x] main de tuiles avec "piochage" quand une tuile est posée
- [x] pose de tuiles
- contraintes de pose de tuile :
  - [x] connexion des couloirs
  - [x] pose adjacente à une autre tuile
- tuiles présentes au départ :
  - [x] une tuile de départ ouverte
  - [x] une tuile avec un marqueur de clé
  - [x] une tuile avec un marqueur de sortie
- [x] indicateur d'équilibre
- mécaniques de score/ :
  - [ ] assemblage de tuiles de couleurs
  - [ ] connexion d'éléments présents sur le plateau au départ
- fin de partie :
  - échec :
    - [x] le plateau est trop déséquilibré
    - [x] il n'est plus possible de connecter la clé à la sortie
  - réussite :
    - [x] la clé est connectée à la sortie

**Comment by Blublusse** [comment]
# Idée pour la suite

# Dungeon builder puis dungeon crawler

Le jeu se déroule en 2 phase :
- la phase de construction du donjon avec pose de tuile et plateau à équilibrer en vue du dessus (enfin un peu en biais)
- la phase d'exploration du donjon en FPS/TPS

# Ramasser des tonneaux

Le joueur doit ramasser des tonneaux disséminés sur le plateau en posant des tuiles et en faisant avancer son personnage. Les tonneaux ont un poids, au fur et à mesure que le joueur les ramasse, le poids se concentre sur son personnage et les déplacements deviennent délicats pour garder le plateau équilibré.

# Dungeon Romantik

Le joueur doit connecter des éléments placés aléatoirement sur le plateau en début de partie en posant des tuiles de couloirs. Tout élément relié à la tuile de départ rapporte des points.
